### PR TITLE
HR-2298 Update retailer morph integration guide

### PR DESCRIPTION
**Pull request by TheGrandPackard**

### CODE REVIEW

**Comment by schuz0r** [comment]
The docs are missing the DropoffMethods endpoint

**Comment by TheGrandPackard** [comment]
I also left out the ReturnReasons endpoint for brevity since these aren't common use cases. I figure we can add those in later (as well as PrintLabel) when it's less time sensitive to round it out the document.

**Comment by schuz0r** [comment]
Yeah that makes sense. PrintLabel isn't an official endpoint, its just what we are using as the callback with the URL field in the label struct (which I figure is also omitted as it is not a standard use case).

**Comment by lawjonathan17** [comment]
**In General** - just reviewed "index.html", easier for me to comment here:
- In the first paragraph, I think "Instances of the morphs exist per platform and custom retailer system." is a bit redundant, the previous sentence pretty much states this.
- I think the ordering of the routes are confusing. I think they should be presented in the order of processing a return. Such as, "Login" should be first. "Gift Login" after. It's strange to read Gift Login first when it's optional and where it needs context of a "customer identity" explained in Login. "Start Return" is also last and after "Finish Return" which is confusing. I think the order would be better read as Login, Gift Login, Get Purchases, Return Options, Preview Return, Start Return, Finish Return, Get Label.
- (aside) I think bullet points are easier to read than paragraphs

**Gift Login**
- See comment of the ordering above. I think it needs the context of the customer identity explained in Login before reading this section. 
- "are required for for authentication" remove extra "for"
- Query - String, Required - The search term to use for searching for purchases. This is the email address if available, otherwise it is the "order ID". should order ID be "order number", first time seeing "order ID" being mentioned, might be confusing


**Get label**
- "The label route is provided the for part of the Hub" remove "the"
- In label response: "The bardcode" -> "barcode"

**Login**
- "returns started at a Kiosk" / "returns available through the Kiosk" - we don't use kiosks anymore right, should this say "return bar" to be more clear
- "through the Get Purchaes" -> "Purchases"
- "email addres" -> "address"

**Preview**
- could use a description of "when" in the response, since that field is shown in the examples

**Get Purchases**
- would be more clear if this appears right after Login
- Special notes: "are already returned should be have" remove "be"
- Data types Returnability: "purchsae" -> "purchase"; Fulfillment - "fulfllied" -> "fulfilled"
- Address object: Province - String, Required - The name of the country of the address. 
Province Code - String, Required - The abbreviation of the country of the address. Province and Province code fields **duplicates** should be country / country code?

**Finish Return**
- "receieved" -> "received" (2 occurrences)

**Return Options**
- response, "Array of Exchange Attributes /Exchange Options" - both don't say if they're required or optional, every other field states these, we should add to be consistent

**Start return**
- "This route is not called for returns started in-store." I think "in-store" can be a bit unclea,, can say "return bar" or on the app. I don't think we said much about "in-store" returns

**Comment by joachimvaldez** [comment]
Here's my feedback in addition to stuff that was already covered:

Should the field names be in the consistent case? In the Data Types sections, I see "Is Gift", "Order Number", etc., but in the example requests and responses, these fields are "isGift", "orderNumber", etc.

Under the "Gift Login" there is "Order Number" and "Zip Code" as fields under "GIFT LOGIN REQUEST". In the example body, there are zipCode and email fields in the request body. The shipping address is mentioned as being collected, but I don't see it in the request or response.

Login endpoint - is "Is Gift" required? It's not in the example response.

I also agree we should add any DropoffMethods and ReturnReasons at some point.

A few minor typos:

- "authentication," -> "authentication."
- "identiy" -> "identity"
- "represent the each line item's" -> "represent each line item's"
- "should be have" -> "should have"
- Maybe when mentioning Thumbnails, Images, say that these values are URLs?

Overall this looks good but honestly it's quite long, so i'm sure i missed things that could be improved. That said, i think we should refer to this document frequently and update it frequently.

**Comment by TheGrandPackard** [comment]
I addressed pretty much all of the feedback that could be addressed. 

I cleaned up the zero timestamps on the return objects that aren't being set so they will be omitted since they don't require documenting. This is done in gomodels and is cleaner because the morph doesn't set that anyways.

As far as the route ordering, it's alphabetical sorting of the routes and I don't have control over that with how the documentation is being generated from the library. I'd like to change the behavior of that in the library we use, but it's going to take time to modify.

I'll check with product on whether they need DropoffMethods and ReturnReasons in with this release of the documentation or not.

**Comment by schuz0r** [comment]
On the description for the gift login I would say that we want to set the query parameter in the identity object to the order id opposed to saying we want to set the identity.

Is the identity actually required in the preview request? From the returnista app I know it gets set the return is a gift return, but I'm not sure about others.

When describing the details object in the purchases endpoint I might mention something about this mostly being morph specific data and outside of the morphs no fields are guaranteed to exist.

In general it might be good to reorder some of these to better match the actual return flow. i.e. have preview after purchases

**Comment by TheGrandPackard** [comment]
I updated the wording for gift login to use query instead of identity since that matches the documentation better.

Customer Identity may not be required for preview, but we do send it.

I added a note about the details information not being guaranteed.

I manually reordered the endpoints for the documentation release, but there is no automated way to do this yet.

**Pull request merged**
